name: Halium Porting Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y git gnupg flex bison gperf build-essential \
          zip bzr curl libc6-dev libncurses5-dev:i386 x11proto-core-dev \
          libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 \
          libgl1-mesa-dev g++-multilib mingw-w64-i686-dev tofrodos \
          python3 python3-markdown libxml2-utils xsltproc zlib1g-dev:i386 \
          schedtool liblz4-tool bc lzop imagemagick libncurses5 rsync \
          python-is-python3

    - name: Create bin directory and update PATH
      run: |
        mkdir -p ~/bin
        echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
        source ~/.bashrc

    - name: Download repo script
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+rx ~/bin/repo

    - name: Initialize Halium source tree
      run: |
        mkdir halium
        cd halium
        repo init -u https://github.com/Halium/android -b halium-9.0 --depth=1
        repo sync -c -j 16

    - name: Add device-specific source
      run: |
        mkdir -p halium/devices/manifests
        cat <<EOF > halium/devices/manifests/sts_a05bd.xml
        <?xml version="1.0" encoding="UTF-8"?>
        <manifest>
          <project path="device/sts/a05bd" name="Maitani-Sakura/android_device_sts_a05bd" remote="github" revision="lineage-16.0" />
        </manifest>
        EOF
        ./halium/devices/setup sts_a05bd

    - name: Initialize build environment
      run: |
        cd halium
        source build/envsetup.sh
        breakfast sts_a05bd

    - name: Modify kernel configuration
      run: |
        cd halium
        git clone https://github.com/mer-hybris/mer-kernel-check
        cd mer-kernel-check
        ./mer_verify_kernel_config ../kernel/sts/a05bd/.config

    - name: Add Hybris patches
      run: |
        cd halium
        hybris-patches/apply-patches.sh --mb

    - name: Build system.img and hybris-boot.img
      run: |
        cd halium
        export USE_HOST_LEX=yes
        mka hybris-boot
        mka systemimage
